name: "JK BMS RS485 MQTT"
version: "0.1.2"
slug: "jk-bms-rs485"
description: "Read JK BMS over RS485 and publish values to MQTT with Home Assistant discovery"
arch:
  - armhf
  - aarch64
  - amd64
init: false
startup: application
boot: manual
stage: stable
homeassistant: "2023.1.0"
url: "https://github.com/9991119990/jk-bms-add--on"
apparmor: true
uart: true
usb: true
devices:
  - /dev/ttyACM0
options:
  serial_port: "/dev/serial/by-id/usb-1a86_USB_Single_Serial_5A9A000831-if00"
  baud: 115200
  address: 0
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_user: ""
  mqtt_password: ""
  interval: 10
schema:
  serial_port: str
  baud: int(110,256000)
  address: int(0,255)
  mqtt_host: str
  mqtt_port: port
  mqtt_user: str?
  mqtt_password: password?
  interval: int(5,300)
